"""Shared helpers for all fetcher scripts.

Design goals:
- Every fetcher runs independently. A failure in one source must never crash
  another or the whole pipeline.
- Each source writes its own raw file into scripts/data_raw/<source>.json.
- Records carry a per-source `online` flag and `last_updated` timestamp so the
  frontend can show stale/offline data honestly instead of silently lying.

Tracked items are loaded from scripts/items.json (generated by gen_items.py).
Each item is variant-aware: stattrak / souvenir / phase.
"""

from __future__ import annotations

import json
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable

import requests

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = ROOT / "scripts" / "data_raw"
PUBLIC_DATA_DIR = ROOT / "public" / "data"
ITEMS_FILE = ROOT / "scripts" / "items.json"
RAW_DIR.mkdir(parents=True, exist_ok=True)
PUBLIC_DATA_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Tracked items. Loaded from items.json; falls back to a tiny inline set so the
# scripts still run before gen_items.py has been executed.
# ---------------------------------------------------------------------------
_FALLBACK_ITEMS = [
    {"item_name": "AK-47 | Redline", "category": "gun", "wear": "Field-Tested",
     "stattrak": False, "souvenir": False, "phase": None},
]


def _load_items() -> list[dict]:
    if ITEMS_FILE.exists():
        try:
            data = json.loads(ITEMS_FILE.read_text(encoding="utf-8"))
            if isinstance(data, list) and data:
                # normalise missing keys
                for it in data:
                    it.setdefault("category", "gun")
                    it.setdefault("stattrak", False)
                    it.setdefault("souvenir", False)
                    it.setdefault("phase", None)
                return data
        except (json.JSONDecodeError, OSError):
            pass
    return list(_FALLBACK_ITEMS)


TRACKED_ITEMS = _load_items()


def now_iso() -> str:
    """UTC timestamp, ISO-8601 with trailing Z."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def variant_key(item: dict) -> str:
    """Stable identity for a variant, including phase (which is NOT in the
    market name). Used to key records across sources."""
    return "|".join([
        item.get("item_name", ""),
        item.get("wear") or "",
        "ST" if item.get("stattrak") else "",
        "SV" if item.get("souvenir") else "",
        item.get("phase") or "",
    ])


def market_hash_name(item: dict) -> str:
    """Steam-style market hash name.

    Rules:
      guns:   'StatTrak™ AK-47 | Redline (Field-Tested)'
              'Souvenir AWP | Dragon Lore (Field-Tested)'
      knives: '★ Karambit | Doppler (Factory New)'
              '★ StatTrak™ Karambit | Doppler (Factory New)'  (ST after the star)

    NOTE: phase (Phase 1..4 / Ruby / Sapphire / Black Pearl / Emerald) is a
    paint attribute and is intentionally NOT part of this name.
    """
    name = item["item_name"]
    st = item.get("stattrak")
    sv = item.get("souvenir")
    wear = item.get("wear")

    if name.startswith("★ "):
        base = name[2:]  # strip the star; re-add after prefixes
        prefix = "StatTrak™ " if st else ""
        core = f"★ {prefix}{base}"
    else:
        prefix = "StatTrak™ " if st else ("Souvenir " if sv else "")
        core = f"{prefix}{name}"

    return f"{core} ({wear})" if wear else core


def request_with_retries(
    url: str,
    *,
    headers: dict | None = None,
    params: dict | None = None,
    retries: int = 3,
    backoff: float = 1.5,
    timeout: int = 15,
) -> requests.Response | None:
    """GET with exponential backoff. Returns None instead of raising so callers
    can flag a source offline without crashing the pipeline."""
    last_err: Exception | None = None
    for attempt in range(retries):
        try:
            resp = requests.get(url, headers=headers, params=params, timeout=timeout)
            if resp.status_code == 200:
                return resp
            last_err = RuntimeError(f"HTTP {resp.status_code}")
        except requests.RequestException as exc:
            last_err = exc
        time.sleep(backoff ** attempt)
    print(f"  ! request failed after {retries} tries: {url} ({last_err})")
    return None


def write_raw(source: str, records: list[dict]) -> None:
    """Persist a source's records to scripts/data_raw/<source>.json."""
    out = {"source": source, "fetched_at": now_iso(), "records": records}
    path = RAW_DIR / f"{source}.json"
    path.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    online = sum(1 for r in records if r.get("online"))
    print(f"  wrote {path.name}: {len(records)} records ({online} online)")


def _base_record(item: dict) -> dict:
    return {
        "item_name": item["item_name"],
        "category": item.get("category", "gun"),
        "wear": item.get("wear"),
        "stattrak": item.get("stattrak", False),
        "souvenir": item.get("souvenir", False),
        "phase": item.get("phase"),
    }


def run_fetcher(source: str, fetch_one: Callable[[dict], dict]) -> None:
    """Run a per-item fetch across TRACKED_ITEMS with isolation.

    `fetch_one(item)` returns at least {"price", "currency", "online"}.
    Any exception for one item is caught and recorded offline so the rest of
    the source still succeeds.
    """
    print(f"[{source}] fetching {len(TRACKED_ITEMS)} variants")
    records: list[dict] = []
    for item in TRACKED_ITEMS:
        try:
            result = fetch_one(item)
        except Exception as exc:
            print(f"  ! {variant_key(item)}: {exc}")
            result = {"price": None, "online": False}
        records.append({
            **_base_record(item),
            "price": result.get("price"),
            "currency": result.get("currency"),
            "online": bool(result.get("online")) and result.get("price") is not None,
            "last_updated": now_iso(),
            "url": result.get("url"),
        })
        time.sleep(result.get("sleep", 0.8))
    write_raw(source, records)
